### ISSUE TITLE
Can not call api for sponsor Enoki

### ISSUE THREAD

**Issue by phapdev** [dantheman8300/enoki-example-app#10]
I have this error when try to call a function with sponsor api in my project with Enoki. But it always throw to me the 'gas_station_error' ( image below). I check the example repo and it was error too ( [https://enoki-example-app.vercel.app/](https://github.com/MystenLabs/sui/issues/url) )

![image](https://github.com/user-attachments/assets/d0984e0e-32f1-4fd9-9d42-6da492be3215)

**Comment by tranvanhai0504** [comment]
I realized that I always get the 401 Unauthorized error. Although I pressed copy private key button from Enoki portal and paste it in to Authorization field. But it not working.

![image](https://github.com/user-attachments/assets/1aad446a-1b18-4c5c-a5ba-a01efebe0b07)

**Comment by phapdev** [comment]
I see the problem has been resolved
